steps:
  # ==========================================
  # 1. BACKEND: Build & Deploy
  # ==========================================
  
  # Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dysarthria-backend', './backend']
    id: 'Build Backend'

  # Push Backend Image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dysarthria-backend']
    id: 'Push Backend'

  # Deploy Backend to Cloud Run
  # Region: asia-southeast2 (Jakarta) - Change if needed
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dysarthria-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dysarthria-backend'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: 'Deploy Backend'

  # ==========================================
  # 2. INTERMEDIATE: Get Backend URL
  # ==========================================
  
  # Fetch the URL of the newly deployed backend service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash'
    args: 
      - '-c'
      - 'gcloud run services describe dysarthria-backend --platform managed --region asia-southeast2 --format "value(status.url)" > /workspace/backend_url.txt && cat /workspace/backend_url.txt'
    id: 'Fetch Backend URL'

  # ==========================================
  # 3. FRONTEND: Build & Deploy
  # ==========================================

  # Build Frontend Image (Injecting Backend URL)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        export BACKEND_URL=$(cat /workspace/backend_url.txt)
        echo "Building Frontend with VITE_API_URL=$BACKEND_URL"
        docker build --build-arg VITE_API_URL=$BACKEND_URL -t gcr.io/$PROJECT_ID/dysarthria-dashboard ./frontend
    id: 'Build Frontend'

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dysarthria-dashboard']
    id: 'Push Frontend'

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dysarthria-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dysarthria-dashboard'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: 'Deploy Frontend'

images:
  - 'gcr.io/$PROJECT_ID/dysarthria-backend'
  - 'gcr.io/$PROJECT_ID/dysarthria-dashboard'

options:
  logging: CLOUD_LOGGING_ONLY
